#!/bin/bash
exec 2>&1

export RAILS_ENV=${RAILS_ENV:="production"}
if [[ -f /etc/service/discourse/.error ]]
then
  exec bash -c \
    "echo 'Refusing to start because there was an error.'; sleep 36864"
fi

source /etc/envars
if [[ -z "$DISCOURSE_SMTP_ADDRESS" ]] || [[ -z "$DISCOURSE_DEVELOPER_EMAILS" ]]
then
  touch /etc/service/discourse/.error
  echo "You have not setup SMTP or Developer Emails, please set them up."
  exit 1
fi

export UNICORN_SIDEKIQS=${UNICORN_SIDEKIQS:=1}
export DISCOURSE_DB_PORT=${DISCOURSE_DB_PORT:=5432}
export DISCOURSE_DB_USER=${DISCOURSE_DB_USER:="discourse"}
export DISCOURSE_DB_HOST=${DISCOURSE_DB_HOST:="postgresql"}
export DISCOURSE_DB_NAME=${DISCOURSE_DB_NAME:="discourse"}
export DISCOURSE_REDIS_HOST=${DISCOURSE_REDIS_HOST:="redis"}
export DISCOURSE_REDIS_PORT=${DISCOURSE_REDIS_PORT:=6379}
export UNICORN_ENABLE_OOBGC=${UNICORN_ENABLE_OOBGC:=0}
export UNICORN_WORKERS=${UNICORN_WORKERS:=2}

touch /opt/discourse/config/discourse.conf
chown discourse.discourse /opt/discourse/config/discourse.conf
for v in $(printenv | grep -P '^DISCOURSE_' | grep -vP '^DISCOURSE_(VERSION|HOME|DATA)'); do
  echo $v | sed -r 's/^DISCOURSE_([^=]+)(.*)/\L\1\E\2/' >> \
    /opt/discourse/config/discourse.conf
done

cd /opt/discourse
sudo -u discourse RAILS_ENV=$RAILS_ENV ruby -S bundle exec rake tmp:create
sudo -u discourse RAILS_ENV=$RAILS_ENV ruby -S bundle exec rake assets:precompile
sudo -u discourse RAILS_ENV=$RAILS_ENV ruby -S bundle exec rake assets:clean
sudo -u discourse RAILS_ENV=$RAILS_ENV ruby -S bundle exec rake db:migrate
sudo -u discourse RAILS_ENV=$RAILS_ENV ruby -S bundle exec rake uploads:clean_up
sudo -u discourse RAILS_ENV=$RAILS_ENV ruby -S bundle exec rake avatars:clean
status=$?

if [[ status -ne 0 ]]
then
  touch /etc/service/discourse/.error
  echo "There was an error migrating the database."
  exit 1
fi

chown -Rh discourse.discourse /opt/discourse
chpst -u discourse \
  ruby -S bundle exec config/unicorn_launcher \
    -E production -c config/unicorn.conf.rb &

pid=$!
while ([[ ! -f tmp/pids/unicorn.pid ]] && [[ $count -lt 24 ]]); do
  let count=$count+1
  sleep 1
done

if [[ ! -f tmp/pids/unicorn.pid ]]
then
  touch /etc/service/discourse/.error
  echo "There was an error starting rails."
  exit 1
else
  # Wait for the log to become available, yeah.
  while ! tail /etc/stdout.d/production.log >/dev/null; do
    sleep 1
  done

  sv restart /etc/service/docker >/dev/null
  wait \
    $pid
fi
